// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMDNBMZCBYNvNV1m1C_7_C0EMjCClx050',
    appId: '1:275139678896:web:512f5fdfcea15ad19ae175',
    messagingSenderId: '275139678896',
    projectId: 'ecommerceapp-483b0',
    authDomain: 'ecommerceapp-483b0.firebaseapp.com',
    storageBucket: 'ecommerceapp-483b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG8Vx8tL_6AWK5jsxJ_ekJ71UCOXzNLJ0',
    appId: '1:275139678896:android:dc99b987cacf0d429ae175',
    messagingSenderId: '275139678896',
    projectId: 'ecommerceapp-483b0',
    storageBucket: 'ecommerceapp-483b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwrqB1EUL7gtkKCUXa2C76Hj97LRBH3w0',
    appId: '1:275139678896:ios:e5af28977e3d6e429ae175',
    messagingSenderId: '275139678896',
    projectId: 'ecommerceapp-483b0',
    storageBucket: 'ecommerceapp-483b0.appspot.com',
    androidClientId: '275139678896-ilcf9msju4lkq2cbqbbq9vhumf2qlol9.apps.googleusercontent.com',
    iosClientId: '275139678896-qarvgs2blubr53fvh192v1p9erkvcjs7.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMDNBMZCBYNvNV1m1C_7_C0EMjCClx050',
    appId: '1:275139678896:web:4fe6221670b409729ae175',
    messagingSenderId: '275139678896',
    projectId: 'ecommerceapp-483b0',
    authDomain: 'ecommerceapp-483b0.firebaseapp.com',
    storageBucket: 'ecommerceapp-483b0.appspot.com',
  );

}